version: "3.8"  # Specify the Docker Compose version

services:
  db:
    build:
      context: ./backend-prueba/postgres
      dockerfile: Dockerfile
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: konecta
      POSTGRES_HOST: db
    
  adminer:
    image: adminer
    restart: always
    ports:
      - "5432:5432"

  nodejs:
    build:
      context: ./backend-prueba
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: ./backend-prueba/.env
    ports:
      - "3000:3000"      
  