version: "3.8"  # Specify the Docker Compose version

services:
  postgres:
    image: postgres:latest  # Use the official latest Postgres image
    environment:
      POSTGRES_USER: postgres # Set an environment variable for the username
      POSTGRES_PASSWORD: admin  # Set an environment variable for the password
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data volume for Postgres

  nodejs-app:
    build: .  # Build the Node.js application from the current directory (replace with your build path if different)
    ports: 
      - "3000:3000"