#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --password "$POSTGRES_PASSWORD" <<-EOSQL
	CREATE TABLE empleados (
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(50) NOT NULL,
  FECHA_INGRESO DATE NOT NULL,
  SALARIO INT NOT NULL
);

CREATE TABLE solicitud(
  ID SERIAL PRIMARY KEY,
  CODIGO VARCHAR(50) NOT NULL,
  DESCRIPCION VARCHAR(50) NOT NULL,
  RESUMEN VARCHAR(50) NOT NULL,
  ID_EMPLEADO INT NOT NULL,
  FOREIGN KEY (ID_EMPLEADO) REFERENCES empleados(ID)
);

CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  id_empleado INT NOT NULL UNIQUE,
  FOREIGN KEY (id_empleado) REFERENCES empleados(ID)
);

INSERT INTO empleados (NOMBRE, FECHA_INGRESO, SALARIO) VALUES ('David Aristizabal', '2024-04-26', 3500000);
EOSQL
