CREATE DATABASE konecta;

\c konecta;

CREATE TABLE empleados (
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(50) NOT NULL,
  FECHA_INGRESO DATE NOT NULL,
  SALARIO INT NOT NULL
);

CREATE TABLE solicitud(
  ID SERIAL PRIMARY KEY,
  CODIGO VARCHAR(50) NOT NULL,
  DESCRIPCION VARCHAR(50) NOT NULL,
  RESUMEN VARCHAR(50) NOT NULL,
  ID_EMPLEADO INT NOT NULL,
  FOREIGN KEY (ID_EMPLEADO) REFERENCES empleados(ID)
);